# Use the official Ubuntu image from the Docker Hub
FROM ubuntu:20.04

# Set the working directory in the container
WORKDIR /app

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the entire project into the container
COPY . .

# Expose the port the app runs on
EXPOSE 8501

# Define the command to run the application
CMD ["streamlit", "run","stream_app.py"]